version: '3'
services:
  application:
    image: scm:latest
    build:
      context: ./Application
      dockerfile: Dockerfile
    command: uvicorn SCM:app --host 0.0.0.0 --port 8000
    container_name: scm
    ports:
      - "8000:8000"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "SCM:1:1"

  server:
    image: server:latest
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: server
    depends_on:
      - kafka
    ports:
      - "8080:8080"


  producer:
    image: producer:latest
    build:
      context: ./Producer
      dockerfile: Dockerfile
    container_name: producer
    depends_on:
      - server
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: SCM
      
  consumer:
    image: consumer:latest
    build:
      context: ./Consumer
      dockerfile: Dockerfile
    container_name: consumer
    depends_on:
      - producer
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: SCM
networks:
  my-network: